In [2]:
import pandas as pd
df=pd.read_csv("sales_data.csv")

In [3]:
df.shape

(40, 8)

In [7]:
df.head(40)

    ID        Date  Product     Category       City    Sales  Quantity  Price
0    1  2024-01-01   Mobile  Electronics      Kochi  12000.0         2   6000
1    2  2024-01-02   Laptop  Electronics      Delhi  50000.0         1  50000
2    3  2024-01-03  T-Shirt     Clothing     Mumbai   4000.0         5    800
3    4  2024-01-04     Rice      Grocery      Kochi   3000.0        60     50
4    5  2024-01-05   Tablet  Electronics  Bangalore  30000.0         2  15000
5    6  2024-01-06    Jeans     Clothing    Chennai   7500.0         5   1500
6    7  2024-01-07    Sugar      Grocery  Hyderabad   4000.0       100     40
7    8  2024-01-08    Saree     Clothing      Delhi  18000.0         9   2000
8    9  2024-01-09    Wheat      Grocery      Kochi   4500.0       100     45
9   10  2024-01-10   Mobile  Electronics     Mumbai  22000.0         2  11000
10  11  2024-01-11   Laptop  Electronics  Bangalore  55000.0         1  55000
11  12  2024-01-12  T-Shirt     Clothing    Chennai   4800.0         6    800
12  13  2024-01-13     Rice      Grocery      Delhi   5000.0       100     50
13  14  2024-01-14   Tablet  Electronics    Kolkata  32000.0         2  16000
14  15  2024-01-15    Jeans     Clothing      Kochi   9000.0         6   1500
15  16  2024-01-16    Sugar      Grocery     Mumbai   4200.0       105     40
16  17  2024-01-17    Saree     Clothing  Bangalore  20000.0        10   2000
17  18  2024-01-18    Wheat      Grocery    Chennai   4700.0       100     47
18  19  2024-01-19   Mobile  Electronics  Hyderabad  21000.0         1  21000
19  20  2024-01-20   Laptop  Electronics      Kochi  60000.0         1  60000
20  21  2024-01-21  T-Shirt     Clothing      Delhi   5600.0         7    800
21  22  2024-01-22     Rice      Grocery    Kolkata   5200.0       104     50
22  23  2024-01-23   Tablet  Electronics     Mumbai  34000.0         2  17000
23  24  2024-01-24    Jeans     Clothing  Bangalore  10500.0         7   1500
24  25  2024-01-25    Sugar      Grocery      Kochi   3800.0        95     40
25  26  2024-01-26    Saree     Clothing    Chennai  22000.0        11   2000
26  27  2024-01-27    Wheat      Grocery      Delhi   4800.0       100     48
27  28  2024-01-28   Mobile  Electronics    Kolkata  23000.0         1  23000
28  29  2024-01-29   Laptop  Electronics     Mumbai  65000.0         1  65000
29  30  2024-01-30  T-Shirt     Clothing      Kochi      NaN         8    800
30  31  2024-02-01     Rice      Grocery  Bangalore   5400.0       108     50
31  32  2024-02-02   Tablet  Electronics    Chennai  36000.0         2  18000
32  33  2024-02-03    Jeans     Clothing  Hyderabad  12000.0         8   1500
33  34  2024-02-04    Sugar      Grocery      Delhi   4000.0       100     40
34  35  2024-02-05    Saree     Clothing    Kolkata  24000.0        12   2000
35  36  2024-02-06    Wheat      Grocery     Mumbai   5000.0       100     50
36  37  2024-02-07   Mobile  Electronics  Bangalore  25000.0         1  25000
37  38  2024-02-08   Laptop  Electronics      Kochi  70000.0         1  70000
38  39  2024-02-09  T-Shirt     Clothing      Delhi   7200.0         9    800
39  40  2024-02-10     Rice      Grocery    Chennai   5600.0       112     50

In [5]:
df.tail()

    ID        Date  Product     Category       City    Sales  Quantity  Price
35  36  2024-02-06    Wheat      Grocery     Mumbai   5000.0       100     50
36  37  2024-02-07   Mobile  Electronics  Bangalore  25000.0         1  25000
37  38  2024-02-08   Laptop  Electronics      Kochi  70000.0         1  70000
38  39  2024-02-09  T-Shirt     Clothing      Delhi   7200.0         9    800
39  40  2024-02-10     Rice      Grocery    Chennai   5600.0       112     50

In [6]:
df.describe()

              ID         Sales    Quantity         Price
count  40.000000     39.000000   40.000000     40.000000
mean   20.500000  18943.589744   35.175000  11765.000000
std    11.690452  18797.561360   45.316487  19992.061846
min     1.000000   3000.000000    1.000000     40.000000
25%    10.750000   4900.000000    2.000000     50.000000
50%    20.500000  10500.000000    7.500000   1500.000000
75%    30.250000  24500.000000  100.000000  16250.000000
max    40.000000  70000.000000  112.000000  70000.000000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        40 non-null     int64
 1   Date      40 non-null     object
 2   Product   40 non-null     object
 3   Category  40 non-null     object
 4   City      40 non-null     object
 5   Sales     39 non-null     float64
 6   Quantity  40 non-null     int64
 7   Price     40 non-null     int64
dtypes: float64(1), int64(3), object(4)
memory usage: 2.6+ KB